export enum AppRoutings {
  Root = '/',
  Login = '/login',
  Dashboard = '/dashboard',
  User = '/users',
  AddUser = "/users/add-user",
  EditUser = "/users/edit-user/:encUserId",
  Stage = "/stage",
  AddStage = '/stage/add',
  EditStage = '/stage/edit/:stageId',
  Leads = "/leads",
  AddLead = "/leads/add",
  ResetPassword = "/reset-password",
  ForgotPassword = "/forgot-password",
  EditLead = '/leads/edit/:leadId',
  ViewLead = '/leads/view/:leadId',
}
